apiVersion: v1
entries:
  pc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-06-30T09:55:09.630313608Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 71b2c204be7acfc2cdb815778669c5b76d0d5e0232bd6571248cc81ee157665c
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: pc
    urls:
    - pc-0.1.0.tgz
    version: 0.1.0
  ptc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-06-30T09:55:09.640533809Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 963478d459f1f819e7a02625ead2edcb9c53830ef111636d881bc032086e9518
    home: ptc.zuid-drecht.nl
    icon: ptc.zuid-drecht.nl
    name: ptc
    urls:
    - ptc-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-30T09:55:09.598374107Z"
