apiVersion: v1
entries:
  ptc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-07-30T10:19:08.6747494Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: e8e66dd67eb7e78ca1b244516d2078bef9da566825ebc45da2346d2cff4741b4
    home: ptc.zuid-drecht.nl
    icon: ptc.zuid-drecht.nl
    name: ptc
    urls:
    - ptc-0.1.0.tgz
    version: 0.1.0
generated: "2020-07-30T10:19:08.6696781Z"
