apiVersion: v1
entries:
  ptc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-09-15T08:56:06.677047Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: ef8a0833d851177bbe54b8fbb02e7522bad7b32072b9cecfaa2929897ae60201
    home: ptc.zuid-drecht.nl
    icon: ptc.zuid-drecht.nl
    name: ptc
    urls:
    - ptc-0.1.0.tgz
    version: 0.1.0
generated: "2020-09-15T08:56:06.6649765Z"
