apiVersion: v1
entries:
  ptc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-08-19T15:25:40.506057033Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 3054e668c4f5a4d3347c5aea21a41d7dabd1c50a711de955a426e05af1f70af9
    home: ptc.zuid-drecht.nl
    icon: ptc.zuid-drecht.nl
    name: ptc
    urls:
    - ptc-0.1.0.tgz
    version: 0.1.0
generated: "2020-08-19T15:25:40.500254333Z"
