apiVersion: v1
entries:
  ptc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-05-25T08:46:29.810305211Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 00f1bdee6feaefd3ca293142cecfc2649caa59823f22bc8df09883441052e3a9
    home: ptc.zaakonline.nl
    icon: ptc.zaakonline.nl
    name: ptc
    urls:
    - ptc-0.1.0.tgz
    version: 0.1.0
generated: "2020-05-25T08:46:29.805400308Z"
