apiVersion: v1
entries:
  ptc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-08-04T08:24:04.007610009Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 9353aa0de31bdc67301f5680063bd20df5c8a46981971a2cc3367611a64d0223
    home: ptc.zuid-drecht.nl
    icon: ptc.zuid-drecht.nl
    name: ptc
    urls:
    - ptc-0.1.0.tgz
    version: 0.1.0
generated: "2020-08-04T08:24:04.004356509Z"
