apiVersion: v1
entries:
<<<<<<< HEAD
  ptc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-07-29T13:24:07.517956764Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 058bf6ee4ed3270ec2d6b4bf519e0f2a58e38bfa021239f05a234e658e03f1b9
=======
<<<<<<< HEAD
  pc:
  - apiVersion: v1
    appVersion: V.0.1
<<<<<<< Updated upstream
    created: "2020-07-27T13:52:54.972432017Z"
=======
    created: "2020-07-27T09:54:38.479301959Z"
>>>>>>> Stashed changes
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: a3ebf537582710b118b706a276db61fec8e25b642f3e8f3d1bb239ac1131f064
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: pc
    urls:
    - pc-0.1.0.tgz
    version: 0.1.0
  ptc:
  - apiVersion: v1
    appVersion: V.0.1
<<<<<<< Updated upstream
    created: "2020-07-27T13:52:54.976549016Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 9586a5499f1f482c7b341143d0fce2c7c68ab5042f89bb5bfcda30d3dd26bf12
=======
  ptc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-07-28T12:28:53.044949254Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 4273d71d5e2e385925b303c87d9ee53e4f787f78297fcd1ec0600fdb7e7e0b55
>>>>>>> development
=======
    created: "2020-07-27T09:54:38.482179459Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: cd17901b579f9bb192d90090b64d2d64b8bbc95a71afcc19e9b65cfaa6e566a2
>>>>>>> Stashed changes
>>>>>>> development
    home: ptc.zuid-drecht.nl
    icon: ptc.zuid-drecht.nl
    name: ptc
    urls:
    - ptc-0.1.0.tgz
    version: 0.1.0
<<<<<<< HEAD
generated: "2020-07-29T13:24:07.514726064Z"
=======
<<<<<<< Updated upstream
<<<<<<< HEAD
generated: "2020-07-27T13:52:54.967576618Z"
=======
generated: "2020-07-28T12:28:53.039472454Z"
>>>>>>> development
=======
generated: "2020-07-27T09:54:38.476566159Z"
>>>>>>> Stashed changes
>>>>>>> development
